# Stage 1: Build Angular application
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build -- --configuration production


# Stage 2: Serve with Nginx
FROM nginx:alpine

COPY --from=build /app/dist/hadiya_products_admin /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
