pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/prajwal9399/Hadiya.git'
            }
        }
        stage('Build Image') {
            steps {
                dir('hadiya_products_backend') {
                    sh 'docker build -t hadiya-backend:latest .'
                }
            }
        }
        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f hadiya-backend-container || true'
            }
        }
        stage('Deploy') {
            steps {
                dir('hadiya_products_backend') {
                    sh '''
                        docker run -d \
                          --name hadiya-backend-container \
                          --env-file .env \
                          -p 3000:3000 \
                          hadiya-backend:latest
                    '''
                }
            }
        }
        stage('Verify') {
            steps {
                sh 'sleep 8 && docker ps | grep hadiya-backend-container'
            }
        }
    }
}
